using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MyApp.SourceGenerators;

/// <summary>
/// Incremental source generator that auto-registers:
///   - All ICommandHandler&lt;,&gt; and IQueryHandler&lt;,&gt; implementations into the DI container.
///   - All classes decorated with [MapToGroup("groupName")] as endpoint mappings.
///
/// Emits a partial implementation of FeaturesExtensions with two partial methods:
///   - AddGeneratedHandlers(IServiceCollection)
///   - MapGeneratedEndpoints(IReadOnlyDictionary&lt;string, RouteGroupBuilder&gt;)
///
/// Also emits the MapToGroupAttribute itself so the main project does not need
/// to define it manually.
/// </summary>
[Generator]
public sealed class FeatureRegistrationGenerator : IIncrementalGenerator
{
    private const string MapToGroupAttributeFullName = "MyApp.Api.Common.Attributes.MapToGroupAttribute";
    private const string CommandHandlerInterfaceName = "ICommandHandler";
    private const string QueryHandlerInterfaceName = "IQueryHandler";
    private const string BehaviorsNamespace = "MyApp.Api.Common.Behaviors";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Emit the MapToGroupAttribute so it is available in the main project
        // without requiring the developer to define it manually.
        context.RegisterPostInitializationOutput(EmitMapToGroupAttribute);

        // Step 2: Find all ICommandHandler<,> and IQueryHandler<,> implementations.
        // Uses syntax-first filtering (fast) followed by semantic confirmation (accurate).
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cls &&
                    cls.BaseList is { Types.Count: > 0 },
                transform: GetHandlerInfo)
            .Where(static h => h is not null)
            .Select(static (h, _) => h!)
            .Collect();

        // Step 3: Find all classes decorated with [MapToGroup("...")] attribute.
        // ForAttributeWithMetadataName is the most efficient API for attribute-based discovery.
        var endpoints = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MapToGroupAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: GetEndpointInfo)
            .Where(static e => e is not null)
            .Select(static (e, _) => e!)
            .Collect();

        // Step 4: Combine both pipelines and emit the generated registration file.
        context.RegisterSourceOutput(
            handlers.Combine(endpoints),
            static (spc, source) => GenerateRegistrations(spc, source.Left, source.Right));
    }

    // -------------------------------------------------------------------------
    // Attribute emission
    // -------------------------------------------------------------------------

    private static void EmitMapToGroupAttribute(IncrementalGeneratorPostInitializationContext ctx)
    {

        ctx.AddSource("MapToGroupAttribute.g.cs", """
            // <auto-generated/>
            // Generated by MyApp.SourceGenerators. Do not edit.
            #nullable enable

            namespace MyApp.Api.Common.Attributes;

            /// <summary>
            /// Marks an endpoint class for automatic route mapping.
            /// The generator will call Map(group) on this class for the specified group.
            /// </summary>
            /// <example>
            /// [MapToGroup("users")]
            /// public static class LoginUserEndpoint { ... }
            /// </example>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            public sealed class MapToGroupAttribute : global::System.Attribute
            {
                /// <summary>
                /// The route group key this endpoint belongs to.
                /// Must match a key in the groups dictionary in FeaturesExtensions.MapFeatures.
                /// </summary>
                public string GroupName { get; }

                public MapToGroupAttribute(string groupName) => GroupName = groupName;
            }
            """);
    }

    // -------------------------------------------------------------------------
    // Handler discovery
    // -------------------------------------------------------------------------

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        if (ctx.Node is not ClassDeclarationSyntax) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol symbol) return null;

        // Skip abstract classes and static classes — they cannot be instantiated by DI
        if (symbol.IsAbstract || symbol.IsStatic) return null;

        foreach (var iface in symbol.AllInterfaces)
        {
            ct.ThrowIfCancellationRequested();

            var original = iface.OriginalDefinition;

            // Match only our two handler interfaces in the correct namespace
            if (original.ContainingNamespace.ToDisplayString() != BehaviorsNamespace) continue;
            if (original.Name != CommandHandlerInterfaceName && original.Name != QueryHandlerInterfaceName) continue;
            if (iface.TypeArguments.Length != 2) continue;

            return new HandlerInfo(
                symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Endpoint discovery
    // -------------------------------------------------------------------------

    private static EndpointInfo? GetEndpointInfo(
        GeneratorAttributeSyntaxContext ctx,
        System.Threading.CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol) return null;

        foreach (var attr in ctx.Attributes)
        {
            ct.ThrowIfCancellationRequested();

            if (attr.ConstructorArguments.Length != 1) continue;
            if (attr.ConstructorArguments[0].Value is not string groupName) continue;

            // Emit a diagnostic and skip if group name is empty
            if (string.IsNullOrWhiteSpace(groupName))
            {
                return new EndpointInfo(
                    symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    string.Empty,
                    ctx.TargetNode.GetLocation());
            }

            // Check that the endpoint has a static Map(RouteGroupBuilder) method
            var hasMapMethod = symbol.GetMembers("Map")
                .OfType<IMethodSymbol>()
                .Any(m => m.IsStatic && m.Parameters.Length == 1);

            if (!hasMapMethod)
            {
                return new EndpointInfo(
                    symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    groupName,
                    ctx.TargetNode.GetLocation(),
                    missingMapMethod: true);
            }

            return new EndpointInfo(
                symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                groupName,
                ctx.TargetNode.GetLocation());
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Code generation
    // -------------------------------------------------------------------------

    private static void GenerateRegistrations(
        SourceProductionContext ctx,
        ImmutableArray<HandlerInfo> handlers,
        ImmutableArray<EndpointInfo> endpoints)
    {
        // Report diagnostics for invalid endpoints before filtering them out
        foreach (var endpoint in endpoints)
        {
            if (string.IsNullOrWhiteSpace(endpoint.GroupName))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.EmptyGroupName,
                    endpoint.Location,
                    endpoint.EndpointFullName));
            }
            else if (endpoint.MissingMapMethod)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MissingMapMethod,
                    endpoint.Location,
                    endpoint.EndpointFullName));
            }
        }

        // Only generate for valid endpoints
        var validEndpoints = endpoints
            .Where(e => !string.IsNullOrWhiteSpace(e.GroupName) && !e.MissingMapMethod)
            .ToArray();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MyApp.SourceGenerators. Do not edit.");
        sb.AppendLine("// Regenerated automatically on every build.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace MyApp.Api.Common.Extensions;");
        sb.AppendLine();
        sb.AppendLine("public static partial class FeaturesExtensions");
        sb.AppendLine("{");

        // --- AddGeneratedHandlers ---
        sb.AppendLine("    /// <summary>Generated DI registrations for all ICommandHandler and IQueryHandler implementations.</summary>");
        sb.AppendLine("    static partial void AddGeneratedHandlers(");
        sb.AppendLine("        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers.OrderBy(h => h.HandlerFullName))
        {
            sb.AppendLine($"        services.AddScoped<{handler.InterfaceFullName}, {handler.HandlerFullName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // --- MapGeneratedEndpoints ---
        sb.AppendLine("    /// <summary>Generated endpoint mappings for all classes decorated with [MapToGroup].</summary>");
        sb.AppendLine("    static partial void MapGeneratedEndpoints(");
        sb.AppendLine("        global::System.Collections.Generic.IReadOnlyDictionary<string, global::Microsoft.AspNetCore.Routing.RouteGroupBuilder> groups)");
        sb.AppendLine("    {");

        var groupedEndpoints = validEndpoints
            .GroupBy(e => e.GroupName)
            .OrderBy(g => g.Key);

        foreach (var group in groupedEndpoints)
        {
            var varName = ToVariableName(group.Key);

            // Throw at startup if the developer forgot to add the group to the dictionary.
            // This gives a clear, actionable error message instead of a silent no-op.
            sb.AppendLine($"        if (!groups.TryGetValue(\"{group.Key}\", out var {varName}))");
            sb.AppendLine($"            throw new global::System.InvalidOperationException(");
            sb.AppendLine($"                \"[MyApp.SourceGenerators] Route group '{group.Key}' is not registered. \"");
            sb.AppendLine($"                + \"Add [\\\"{group.Key}\\\"] to the groups dictionary in FeaturesExtensions.MapFeatures.\");");
            sb.AppendLine();

            foreach (var endpoint in group.OrderBy(e => e.EndpointFullName))
            {
                sb.AppendLine($"        {endpoint.EndpointFullName}.Map({varName});");
            }

            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("FeatureRegistrations.g.cs", sb.ToString());
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Converts a group name to a valid C# variable name.
    /// e.g. "users" → "usersGroup", "user-profiles" → "userProfilesGroup"
    /// </summary>
    private static string ToVariableName(string groupName)
    {
        var sb = new StringBuilder();
        bool capitalizeNext = false;

        foreach (var ch in groupName)
        {
            if (ch == '-' || ch == '_' || ch == '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (!char.IsLetterOrDigit(ch)) continue;

            sb.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
            capitalizeNext = false;
        }

        if (sb.Length == 0) return "unknownGroup";

        // Ensure first char is lowercase (camelCase)
        sb[0] = char.ToLowerInvariant(sb[0]);
        sb.Append("Group");

        return sb.ToString();
    }
}

// -------------------------------------------------------------------------
// Data records
// -------------------------------------------------------------------------

internal sealed class HandlerInfo
{
    public string HandlerFullName { get; }
    public string InterfaceFullName { get; }

    public HandlerInfo(string handlerFullName, string interfaceFullName)
    {
        HandlerFullName = handlerFullName;
        InterfaceFullName = interfaceFullName;
    }
}

internal sealed class EndpointInfo
{
    public string EndpointFullName { get; }
    public string GroupName { get; }
    public Location? Location { get; }
    public bool MissingMapMethod { get; }

    public EndpointInfo(string endpointFullName, string groupName, Location? location = null, bool missingMapMethod = false)
    {
        EndpointFullName = endpointFullName;
        GroupName = groupName;
        Location = location;
        MissingMapMethod = missingMapMethod;
    }
}
